---
- hosts: webservers
  #sudo: yes
  become: yes
  become_user: ansible_sa
  become_method: su
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/ansible/
    max_clients: 5
  vars_prompt:
  - name: username
    prompt: What is your name?


  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

  - name: Deploy configuration File
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
     - Restart Apache
    
  - name: Copy Site Files
    template: src=templates/index.j2 dest={{ doc_root }}/index.html

    handlers:
     - name: Restart Apache
     - service: name=httpd state=restarted


- hosts: dbservers
  #sudo: yes
  become: yes
  become_user: ansible_sa
  become_method: su

  tasks:
  - name: Ensure MariaDB is installed
    yum: name=mariadb state=present
    when: ansible_os_family == "RedHat"
  
  - name: Start MariaDB service
    service: name=mariadb state=started

- hosts: webservers:dbservers
  #sudo: yes
  become: yes
  become_user: ansible_sa
  become_method: su

  tasks:
  - name: Turn off firewall
    service: name=firewalld state=stopped

  - name: Disable firewalld
    service: name=firewalld enabled=no state=stopped

