---
- hosts: webservers
  #sudo: yes
  become: yes
  become_user: ansible_sa
  become_method: su
  
  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

- hosts: dbservers
  #sudo: yes
  become: yes
  become_user: ansible_sa
  become_method: su

  tasks:
  - name: Ensure MariaDB is installed
    yum: name=mariadb state=present
  
  - name: Start MariaDB service
    service: name=mariadb state=started

- hosts: webservers:dbservers
  #sudo: yes
  become: yes
  become_user: ansible_sa
  become_method: su

  tasks:
  - name: Turn off firewall
    service: name=firewalld state=stopped

  - name: Disable firewalld
    service: name=firewalld enabled=no state=stopped

